build(deps): Bump plugin.serialization from 1.7.20 to 1.7.22 in /api-editor (#1132)
Bumps [plugin.serialization](https://github.com/JetBrains/kotlin) from
1.7.20 to 1.7.22.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/JetBrains/kotlin/releases">plugin.serialization's
releases</a>.</em></p>
<blockquote>
<h2>Kotlin 1.7.22</h2>
<p><strong>This is a technical release.</strong> It doesn't contain any
fixes that aren't included in <a
href="https://github.com/JetBrains/kotlin/releases/tag/v1.7.21">Kotlin
1.7.21</a>.
Version 1.7.22 of the Kotlin plugin will not be available for
downloading or installing in any IDEs.</p>
<h2>Checksums</h2>
<table>
<thead>
<tr>
<th>File</th>
<th>Sha256</th>
</tr>
</thead>
<tbody>
<tr>
<td>kotlin-compiler-1.7.22.zip</td>

<td>9db4b467743c1aea8a21c08e1c286bc2aeb93f14c7ba2037dbd8f48adc357d83</td>
</tr>
<tr>
<td>kotlin-native-linux-x86_64-1.7.22.tar.gz</td>

<td>dd004d520056aba67f2955a3bec5af75f8f2d78b179d4b5f733a77e3eef57aff</td>
</tr>
<tr>
<td>kotlin-native-macos-x86_64-1.7.22.tar.gz</td>

<td>153fa411fa8c993ce2635e2504e9b102cb05362cc794b66ef9def26a78b427b5</td>
</tr>
<tr>
<td>kotlin-native-macos-aarch64-1.7.22.tar.gz</td>

<td>4ffcd76c77cc824eff8addd5e2a73da4f3bbd3584fa9ef282b3f669c45426b1e</td>
</tr>
<tr>
<td>kotlin-native-windows-x86_64-1.7.22.zip</td>

<td>3bccd23479848ec61c56ed5760010456d17acbe88a00a1f10fb38eae256f2e92</td>
</tr>
</tbody>
</table>
<h2>Kotlin 1.7.21</h2>
<h2>Changelog</h2>
<h3>Compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54463"><code>KT-54463</code></a>
Delegating to a field with a platform type causes
java.lang.NoSuchFieldError: value$delegate</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54509"><code>KT-54509</code></a>
Ir Interpreter: unable to evaluate string concatenation with
&quot;this&quot; as argument</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54004"><code>KT-54004</code></a>
Builder type inference does not work correctly with variable assignment
and breaks run-time</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54393"><code>KT-54393</code></a>
Change in behavior from 1.7.10 to 1.7.20 for java field override.</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54615"><code>KT-54615</code></a>
JVM: Internal error in file lowering: java.lang.AssertionError: Error
occurred while optimizing an expression</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54581"><code>KT-54581</code></a>
JVM: &quot;VerifyError: Bad type on operand stack&quot; with generic
inline function and <code>when</code> inside try-catch block</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-53146"><code>KT-53146</code></a>
JVM IR: unnecessary checkcast of null leads to NoClassDefFoundError if
the type isn't available at runtime</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54600"><code>KT-54600</code></a>
NPE on passing nullable Kotlin lambda as Java's generic SAM interface
with <code>super</code> type bound</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54707"><code>KT-54707</code></a>
&quot;VerifyError: Bad type on operand stack&quot; in inline call chain
on a nullable array value</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54650"><code>KT-54650</code></a>
Binary incompatible ABI change in Kotlin 1.7.20</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54802"><code>KT-54802</code></a>
&quot;VerifyError: Bad type on operand stack&quot; for inline functions
on arrays</li>
</ul>
<h3>Native. Runtime. Memory</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54498"><code>KT-54498</code></a>
Deprecation message of 'FreezingIsDeprecated' is not really helpful</li>
</ul>
<h3>Tools. Gradle. Multiplatform</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54387"><code>KT-54387</code></a>
Remove MPP alpha stability warning</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-48436"><code>KT-48436</code></a>
False positive &quot;The Kotlin source set androidAndroidTestRelease was
configured but not added to any Kotlin compilation&quot;</li>
</ul>
<h3>Tools. JPS</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-45474"><code>KT-45474</code></a>
False positive NO_ELSE_IN_WHEN on sealed class with incremental
compilation</li>
</ul>
<h2>Checksums</h2>
<table>
<thead>
<tr>
<th>File</th>
<th>Sha256</th>
</tr>
</thead>
</table>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/JetBrains/kotlin/blob/master/ChangeLog.md">plugin.serialization's
changelog</a>.</em></p>
<blockquote>
<h2>1.7.21</h2>
<h3>Compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54463"><code>KT-54463</code></a>
Delegating to a field with a platform type causes
java.lang.NoSuchFieldError: value$delegate</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54509"><code>KT-54509</code></a>
Ir Interpreter: unable to evaluate string concatenation with
&quot;this&quot; as argument</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54004"><code>KT-54004</code></a>
Builder type inference does not work correctly with variable assignment
and breaks run-time</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54393"><code>KT-54393</code></a>
Change in behavior from 1.7.10 to 1.7.20 for java field override.</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54615"><code>KT-54615</code></a>
JVM: Internal error in file lowering: java.lang.AssertionError: Error
occurred while optimizing an expression</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54581"><code>KT-54581</code></a>
JVM: &quot;VerifyError: Bad type on operand stack&quot; with generic
inline function and <code>when</code> inside try-catch block</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-53146"><code>KT-53146</code></a>
JVM IR: unnecessary checkcast of null leads to NoClassDefFoundError if
the type isn't available at runtime</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54600"><code>KT-54600</code></a>
NPE on passing nullable Kotlin lambda as Java's generic SAM interface
with <code>super</code> type bound</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54707"><code>KT-54707</code></a>
&quot;VerifyError: Bad type on operand stack&quot; in inline call chain
on a nullable array value</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54650"><code>KT-54650</code></a>
Binary incompatible ABI change in Kotlin 1.7.20</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54802"><code>KT-54802</code></a>
&quot;VerifyError: Bad type on operand stack&quot; for inline functions
on arrays</li>
</ul>
<h3>Native. Runtime. Memory</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54498"><code>KT-54498</code></a>
Deprecation message of 'FreezingIsDeprecated' is not really helpful</li>
</ul>
<h3>Tools. Gradle. Multiplatform</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54387"><code>KT-54387</code></a>
Remove MPP alpha stability warning</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-48436"><code>KT-48436</code></a>
False positive &quot;The Kotlin source set androidAndroidTestRelease was
configured but not added to any Kotlin compilation&quot;</li>
</ul>
<h3>Tools. JPS</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-45474"><code>KT-45474</code></a>
False positive NO_ELSE_IN_WHEN on sealed class with incremental
compilation</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/JetBrains/kotlin/commit/be3c5a5310abb619f8960f12af170683af4b0f9b"><code>be3c5a5</code></a>
Instruction for building 1.7.21 release</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/80eb82acc22629d39a513ca2c21a14f4982ddce6"><code>80eb82a</code></a>
Instructions for building 1.7.20 release</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/cb5180394bc3bd801e4607e8f6e051b3bc707e28"><code>cb51803</code></a>
Scripts for building Kotlin repository</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/7784d1025e8cf091acff524ff4426c52c2f77d2d"><code>7784d10</code></a>
Change bootstrap to 1.7.21-release-254</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/e7f77e9d35483cf3d428f5c9a2eecc98d6cbb3aa"><code>e7f77e9</code></a>
Keep track of array types in OptimizationBasicInterpreter</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/7deaab9cbd635210c753f3cc733cfc720117b86f"><code>7deaab9</code></a>
Edit changelog for 1.7.21</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/0b49dc2248c29344901ea8b6e5fe7c45fa8d653b"><code>0b49dc2</code></a>
Fix binary compatibility for inlined local delegated properies</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/90b3e21fa1f6fa5ed8d944d80f40767f563cdcd9"><code>90b3e21</code></a>
Advance bootstrap to 1.7.21</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/c55a1976c21007734d48489eeca1aa90f3524455"><code>c55a197</code></a>
Edit changelog for 1.7.21</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/b1b18c2282f63f7e81fc9e5cbfc984f0392506ee"><code>b1b18c2</code></a>
Add regression test for KT-54707</li>
<li>Additional commits viewable in <a
href="https://github.com/JetBrains/kotlin/compare/v1.7.20...v1.7.22">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=plugin.serialization&package-manager=gradle&previous-version=1.7.20&new-version=1.7.22)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>